"""increase image column size for cloudinary urls

Revision ID: 125bab48aca3
Revises: dba770dffdf2
Create Date: 2026-07-07 12:38:10.001440

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '125bab48aca3'
down_revision = 'dba770dffdf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_images', schema=None) as batch_op:
        batch_op.alter_column('filename',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=False)

    with op.batch_alter_table('user_notes', schema=None) as batch_op:
        batch_op.alter_column('image_filename',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_notes', schema=None) as batch_op:
        batch_op.alter_column('image_filename',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=True)

    with op.batch_alter_table('user_images', schema=None) as batch_op:
        batch_op.alter_column('filename',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###
