"""Add image folders and images tables

Revision ID: 40360d58b231
Revises: 8a3d3fc624eb
Create Date: 2025-08-08 11:17:31.392568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40360d58b231'
down_revision = '8a3d3fc624eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_folder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'user_id', name='unique_folder_per_user')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['image_folder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    op.drop_table('image_folder')
    # ### end Alembic commands ###
