"""user_notes table

Revision ID: 492c5a3b625d
Revises: 63bf30cb2c4b
Create Date: 2025-06-20 18:50:43.975577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '492c5a3b625d'
down_revision = '63bf30cb2c4b'
branch_labels = None
depends_on = None


def upgrade():
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_notes')
    # ### end Alembic commands ###
