"""user_notes table

Revision ID: 492c5a3b625d
Revises: 63bf30cb2c4b
Create Date: 2025-06-20 18:50:43.975577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '492c5a3b625d'
down_revision = '63bf30cb2c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('note_name', sa.String(length=70), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('source_links', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_notes')
    # ### end Alembic commands ###
