"""Add image_filename column to UserNotes Table

Revision ID: 8a3d3fc624eb
Revises: 492c5a3b625d
Create Date: 2025-07-29 17:00:10.116807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a3d3fc624eb'
down_revision = '492c5a3b625d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_notes', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
