"""Changed table name to user_images

Revision ID: dba770dffdf2
Revises: 40360d58b231
Create Date: 2025-08-08 11:41:34.622181

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dba770dffdf2'
down_revision = '40360d58b231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['image_folder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('images')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('folder_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['image_folder.id'], name=op.f('images_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('user_images')
    # ### end Alembic commands ###
